### ISSUE TITLE
Difficult to use DriverConfigs with Bootstrap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-sdk-go#324]
Currently, the [documented](https://docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html) way to create a device service driver is to create a `ProtocolDriver` implementation and then pass an instance of that along to `service.Bootstrap`. However, this makes it difficult to get information from the `Driver` section of configuration.toml before setting up the `ProtocolDriver` instance.

For example, in my case I am connecting to a BLE device and want to connect to that device and include that device info in the `ProtocolDriver`, but I need the BLE address in order to make the connection. My intention was to store this information in the `Driver` section of the configuration.toml file, but doing so is difficult.

* Attempting to use `device.DriverConfigs()` before calling `service.Bootstrap` results in a nil pointer derefence:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x168 pc=0xa2ee2c]

goroutine 7 [running]:
github.com/edgexfoundry/device-sdk-go.DriverConfigs(...)
        /home/me/go/pkg/mod/github.com/edgexfoundry/device-sdk-go@v0.0.0-20190619143639-9c16751eb33b/service.go:289
main.run(0xc000186000, 0xc0001203c0, 0x0, 0x0, 0x0)
        /home/me/git/edgex/device-thingy52/cmd/main.go:104 +0x29c
main.main.func1(0xc000186000, 0xc0001203c0)
        /home/me/git/edgex/device-thingy52/cmd/main.go:223 +0x39
created by main.main
        /home/me/git/edgex/device-thingy52/cmd/main.go:222 +0xd8
```
* My device service could in theory eventually connect to multiple physical devices simultaneously, so it doesn't make sense to get the address from the configuration file during the `Initialize` method which will only be called once per device service and not once per device AFAICT 
* Ideally it seems like I would be putting the BLE address inside the `DeviceList.Protocols` specification in the configuration.toml, but I don't see how to access these at all when using `service.Bootstrap`

**Comment by cloudxxx8** [comment]
not only DriverConfigs and DeviceList, all configuration hasn't been loaded before service.NewService().
It's correct to put the address into DeviceList.Protocols, and it's the issue I mentioned in #276
The BLE address should be handled when each device creation, not the protocol driver initialization.  We need the device create or connect callback to solve this issue.

**Comment by anonymouse64** [comment]
How can we create the device/initialize the actual BLE connection before the `DeviceList` has been created? 

I've since refactored my device service to not use `Bootstrap` but still has the issue described in #276 and it can't access the `Devices` from the `DeviceList` in the configuration.toml until after `Start` was called.

It would be nice if there was a separate method from `Start` that would simply initialize enough of the device service such that we could read `DriverConfigs` and `Devices` from the service but not, for example, start the `AutoEvents` or call the `ProtocolDriver` `Initialize` method or start the HTTP server to service commands, etc.

**Comment by cloudxxx8** [comment]
@anonymouse64 sorry, I don't understand the use case here.  Do you need a Device Service initialization, but it is not `ProtocolDriver.Initialize`?  Why can't it be `ProtocolDriver.Initialize` plus the new Device creation callback in `ProtocolDriver`?

**Comment by anonymouse64** [comment]
> Do you need a Device Service initialization, but it is not `ProtocolDriver.Initialize`?

Yes, because I also want to access generic configuration from `DriverConfigs` before setting up any devices.

Once the device creation callback in ProtocolDriver is available that will be enough for connecting to the devices before HandleReadCommand, etc. but that won't cover my use case with accessing the device driver configuration `Driver` section in the configuration.toml.

**Comment by cloudxxx8** [comment]
@anonymouse64 I thought the easy solution is to move `ProtocolDriver.Initialize` call to right after the loading configuration and before `InitCache` in `service.Start`
Then, you could put your logic into `ProtocolDriver.Initialize`
Is it ok with you?

**Comment by anonymouse64** [comment]
I would think that the cache of devices should be initialized by the time that Initialize is called so that before we have a register callback in the ProtocolDriver we could access the cache of devices in the Initialize method

**Comment by cloudxxx8** [comment]
how about after initCache and before provision.LoadDevices which is loading DeviceList from configuration?

**Comment by cloudxxx8** [comment]
@anonymouse64 please see whether #331 can meet your requirement

**Comment by anonymouse64** [comment]
@cloudxxx8 unfortunately that solution doesn't seem like it would solve anything.

To be clear, I specifically want to be able to access DriverConfig before calling `service.Start` (or equivalently `service.Bootstrap`) for driver level configuration. This issue is specifically about driver level configuration in the configuration.toml and using it before starting the SDK service running.

I would also like to have the methods proposed in #276 for accessing stuff like Protocols from the DeviceList, but that's an orthogonal request I think.

**Comment by cloudxxx8** [comment]
@anonymouse64 The driver level logic should be put in protocol driver, not bootstrap.
Could the proposed resolution in #276 totally solve your problem?

**Comment by cloudxxx8** [comment]
@anonymouse64 #276 has been resolved.  May we close this issue?

**Comment by anonymouse64** [comment]
I will need to update my driver to use the new methods in #276, it's not clear to me yet whether that will solve my specific use case with my [device-thingy52](https://github.com/anonymouse64/device-thingy52), but as mentioned above, I still intend this as an orthogonal request to #276, but since you disagree I need to put together an example of what I can't do without this request.

**Comment by cloudxxx8** [comment]
@anonymouse64 we had better put all the driver related logic into protocol driver.  the responsibility of Bootstrap is not loading config.  please advise how to resolve your issue.  thanks

**Comment by hahattan** [comment]
@anonymouse64 did you resolve this in the end? 
SDK is now using `go-mod-bootstrap` package but I think it's still unable to access `DriverConfig` before calling `Bootstrap`

you can access `DriverConfig` in `protocolDriver.Initialize` via something like
```
config := sdk.DriverConfigs()
# do something with the config
...
```

**Comment by anonymouse64** [comment]
unfortunately I don't have the bandwidth to look into this at all, sorry. [My repo](https://github.com/anonymouse64/device-thingy52/tree/master) is still available if someone wants to take a stab at updating it to "do the right thing" with the updated sdk methods, patches welcome :smile:

**Comment by tonyespy** [comment]
The original design of device-sdk-go was modeled after the go **net/http** package's `Server`, and as such allowed a new `Service` instance to be created and customized before being started. The initial version of the SDK also included an optional **startup** package which provided the `Bootstrap` function which handled basic DS command-line arguments, created a new `Service`, setup a signal handler, and then called `Service.Start`. This was meant as the easy way to spin up a new device service.

For power users, the recommended approach was to create the `Service` instance directly, configure it, and call `Service.Start` if/when ready. That said, it still would not have been possible to access the `DriverConfigs` before passing the `ProtocolDriver` implementation to the SDK, as `ProtocolDriver` was a required parameter of `device.NewService`, and `NewService` was responsible for loading configuration. 

After reviewing the comment history of this issue, per @hahattan's last comment, it should be possible to use `service.DriverConfigs` to access the **[Driver]** configuration options from within `ProtocolDriver.Initialize` method. In fact, device-mqtt-go does this:

https://github.com/edgexfoundry/device-mqtt-go/blob/master/internal/driver/driver.go#L65

As such, I'm closing this issue.

Finally, as an aside, during the Geneva dev cycle, device-go-sdk was re-factored to use go-mod-bootstrap for service initialization. While it still might be possible to write a device service without using the **startup** package, it's become much more complicated to do so, and AFAICT there's no documentation for how to do so... I also question whether the removal of the top-level **device** package in the SDK (now subsumed by **pkg/service**) was a breaking API change?
