### ISSUE TITLE
Event sending got EOF error

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/device-sdk-go#657]
Device service sometimes got the EOF error when setup a lot of auto events.

```
level=ERROR ts=2020-11-23T10:23:03.03951356Z app=edgex-device-modbus source=utils.go:95 device=device-10948 response= error="Post \"http://edgex-core-data:48080/api/v1/event\": EOF" msg="SendEvent Failed to push event"
```

We got this error when running the [Modbus scalability test](https://github.com/edgexfoundry/edgex-taf/pull/178), the error occurs when the device amount increase then 200, and each device contains 4 auto event with 1, 2, 3, 4 seconds frequency respectively.

**Comment by cloudxxx8** [comment]
sendEvent is an async call in Go SDK, and we should limit the concurrent call volume to prevent this error.
Using `AsyncBufferSize` is a proposed solution, and we should rename it to `BufferSize` in v2.

**Comment by jpwhitemn** [comment]
Per 1/4/21 device service meeting - we decided that this issue should be put on hold and we point people to the new message bus implementation if message durability and no loss of events is critical.  **If time permits**, we'll build better flow control for REST implementation for EdgeX 2.0.  We will not address this issue for EdgeX 1.x.

**Comment by cloudxxx8** [comment]
this issue is resolved by the message bus usage in V2
@jpwhitemn please see whether we can close this issue

**Comment by tonyespy** [comment]
@cloudxxx8 isn't this the bug that caused us to release 1.3.1 and device-sdk-go 1.4.0 w/the ZMQ fix?

**Comment by cloudxxx8** [comment]
@tonyespy no, this is for Core Data REST API limitation

**Comment by anilchoudhury** [comment]
Hi,

I am running EdgeX on RPI with docker-compose script: https://github.com/edgexfoundry/edgex-compose/blob/master/docker-compose-no-secty-arm64.yml. I think its running Ireland pre-release version.
I am running the EdgeX on my RPI4.
I have changed the ip address from 127.0.0.1 to 0.0.0.0 to communicate with the micro services from dev machines.

I am still getting same error:
```
edgex-device-virtual | level=ERROR ts=2021-05-30T13:21:47.46675544Z app=device-virtual source=utils.go:78 msg="Failed to push event to Coredata: failed to send a http request -> Post \"http://edgex-core-data:59880/api/v2/event/Random-Integer-Device/Random-Integer-Device/Int64\": EOF"
edgex-device-virtual | level=ERROR ts=2021-05-30T13:22:47.48908351Z app=device-virtual source=utils.go:78 msg="Failed to push event to Coredata: failed to send a http request -> Post \"http://edgex-core-data:59880/api/v2/event/Random-Integer-Device/Random-Integer-Device/Int8\": read tcp 172.19.0.11:50902->172.19.0.8:59880: read: connection reset by peer"
edgex-device-virtual | level=ERROR ts=2021-05-30T13:35:42.686460431Z app=device-virtual source=utils.go:78 msg="Failed to push event to Coredata: request failed, status code: 409, err: {\"apiVersion\":\"v2\",\"requestId\":\"7a987c61-32b8-441c-8fb9-3b633272233b\",\"message\":\"Event Id exists\",\"statusCode\":409}\n"
```
I think this version supports message bus but there is no container service for message bus broker.

Event count check on core data: http://192.168.0.104:59880/api/v2/event/count
{"apiVersion":"v2","statusCode":200,"Count":25031}

**Comment by cloudxxx8** [comment]
@anilchoudhury the default message broker is Redis, but you need to enable this configuration by changing it to true
https://github.com/edgexfoundry/device-virtual-go/blob/8d9cac7b544984367de20437773925dcf3f7e06d/cmd/res/configuration.toml#L86

We are resolving the issue you encountered and monitoring it in this issue https://github.com/edgexfoundry/edgex-go/issues/3497

Use message bus could work around this issue for now.

**Comment by anilchoudhury** [comment]
@cloudxxx8 I am using docker-compose to run these services. Where can i edit these settings as these are not available in docker-compose script.

**Comment by cloudxxx8** [comment]
You can use the environment variable override through the docker-compose file
Add a variable in this section
https://github.com/edgexfoundry/edgex-compose/blob/0e6e507ec88921f14d14a42a0d8b3e878549efea/docker-compose-no-secty-arm64.yml#L187-L197
DEVICE_USEMESSAGEBUS="true"

**Comment by anilchoudhury** [comment]
Thanks for the quick help. I am not getting the error any more.
How can we sniff the message bus to see all events are getting pushed on the message bus?

Also another question, as edgeX has multiple instance of Redis DB, which instance and port is managing the message bus? Is it the core-data?
Sorry for the novice queries.

**Comment by lenny-intel** [comment]
@iain-anderson , @cloudxxx8 , can this one now be closed? i.e. fix by using MessageBus.

**Comment by cloudxxx8** [comment]
right, message bus path resolves this issue
